name: Krypto

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: antoniouaa/krypto@master
      with:
        dir: "."
      env:
        TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}